

USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMM_DB;
USE SCHEMA MART;


CREATE OR REPLACE TABLE SALES_SUMMARY AS
SELECT
    order_date,
    COUNT(order_id) AS total_orders,
    SUM(order_amount) AS total_sales,
    AVG(order_amount) AS average_sales
FROM CORE.CORE_ORDERS
GROUP BY order_date;

CREATE OR REPLACE TABLE TOP_CUSTOMERS AS
SELECT
    customer_id,
    SUM(order_amount) AS total_spent
FROM CORE.CORE_ORDERS
GROUP BY customer_id
ORDER BY total_spent DESC;


-- PAYMENT ANALYSIS TABLE


CREATE OR REPLACE TABLE PAYMENT_ANALYSIS AS
SELECT
    payment_method,
    COUNT(payment_id) AS total_payments,
    SUM(payment_amount) AS total_amount
FROM CORE.CORE_PAYMENT
GROUP BY payment_method;


-- FAILED PAYMENTS TABLE

CREATE OR REPLACE TABLE FAILED_PAYMENTS AS
SELECT *
FROM CORE.CORE_PAYMENT
WHERE payment_status = 'Failed';


-- CART ABANDONMENT TABLE

CREATE OR REPLACE TABLE CART_ABANDONMENT AS
SELECT
    cart_id,
    customer_id,
    created_at

FROM CORE.CORE_CART
WHERE status = 'Abandoned';

-- PRODUCT PERFORMANCE TABLE

CREATE OR REPLACE TABLE PRODUCT_PERFORMANCE AS
SELECT
    category,
    COUNT(product_id) AS total_products,
    AVG(price) AS average_price
FROM CORE.CORE_PRODUCT
GROUP BY category;


-- CUSTOMER CITY ANALYSIS


CREATE OR REPLACE TABLE CUSTOMER_CITY_ANALYSIS AS
SELECT
    city,
    COUNT(customer_id) AS total_customers
FROM CORE.CORE_CUSTOMER
GROUP BY city;


-- DAILY ORDER STATUS REPORT

CREATE OR REPLACE TABLE DAILY_ORDER_STATUS AS
SELECT
    order_status,
    COUNT(order_id) AS total_orders
FROM CORE.CORE_ORDERS
GROUP BY order_status;


-- EVENT ANALYTICS TABLE

CREATE OR REPLACE TABLE EVENT_ANALYTICS AS
SELECT
    event_type,
    COUNT(product_id) AS total_events
FROM CORE.CORE_CUSTOMER_EVENTS
GROUP BY event_type;


-- VERIFY MART TABLES

SELECT * FROM SALES_SUMMARY;

SELECT * FROM TOP_CUSTOMERS;

SELECT * FROM PAYMENT_ANALYSIS;

SELECT * FROM FAILED_PAYMENTS;

SELECT * FROM CART_ABANDONMENT;

SELECT * FROM PRODUCT_PERFORMANCE;

SELECT * FROM CUSTOMER_CITY_ANALYSIS;

SELECT * FROM DAILY_ORDER_STATUS;

SELECT * FROM EVENT_ANALYTICS;