

USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMM_DB;

-- CREATE ROLES

CREATE OR REPLACE ROLE ADMIN_ROLE;

CREATE OR REPLACE ROLE ANALYST_ROLE;

CREATE OR REPLACE ROLE DEVELOPER_ROLE;

CREATE OR REPLACE ROLE VIEWER_ROLE;

SHOW ROLES;


-- GRANT WAREHOUSE ACCESS


GRANT USAGE
ON WAREHOUSE ECOMMERCE_WH
TO ROLE ADMIN_ROLE;

GRANT USAGE
ON WAREHOUSE ECOMMERCE_WH
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON WAREHOUSE ECOMMERCE_WH
TO ROLE DEVELOPER_ROLE;

GRANT USAGE
ON WAREHOUSE ECOMMERCE_WH
TO ROLE VIEWER_ROLE;


-- GRANT DATABASE ACCESS


GRANT USAGE
ON DATABASE ECOMM_DB
TO ROLE ADMIN_ROLE;

GRANT USAGE
ON DATABASE ECOMM_DB
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON DATABASE ECOMM_DB
TO ROLE DEVELOPER_ROLE;

GRANT USAGE
ON DATABASE ECOMM_DB
TO ROLE VIEWER_ROLE;


-- GRANT SCHEMA ACCESS


GRANT USAGE
ON SCHEMA RAW
TO ROLE DEVELOPER_ROLE;

GRANT USAGE
ON SCHEMA CORE
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON SCHEMA MART
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON SCHEMA MART
TO ROLE VIEWER_ROLE;


-- GRANT TABLE PRIVILEGES


-- RAW LAYER

GRANT SELECT, INSERT, UPDATE
ON ALL TABLES IN SCHEMA RAW
TO ROLE DEVELOPER_ROLE;

-- CORE LAYER

GRANT SELECT
ON ALL TABLES IN SCHEMA CORE
TO ROLE ANALYST_ROLE;

-- MART LAYER

GRANT SELECT
ON ALL TABLES IN SCHEMA MART
TO ROLE ANALYST_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA MART
TO ROLE VIEWER_ROLE;


-- FUTURE TABLE ACCESS


GRANT SELECT
ON FUTURE TABLES IN SCHEMA MART
TO ROLE VIEWER_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA CORE
TO ROLE ANALYST_ROLE;


-- CREATE SAMPLE USERS


CREATE OR REPLACE USER analyst_user
PASSWORD = 'Analyst@123'
DEFAULT_ROLE = ANALYST_ROLE
DEFAULT_WAREHOUSE = ECOMMERCE_WH;

CREATE OR REPLACE USER developer_user
PASSWORD = 'Developer@123'
DEFAULT_ROLE = DEVELOPER_ROLE
DEFAULT_WAREHOUSE = ECOMMERCE_WH;

CREATE OR REPLACE USER viewer_user
PASSWORD = 'Viewer@123'
DEFAULT_ROLE = VIEWER_ROLE
DEFAULT_WAREHOUSE = ECOMMERCE_WH;


-- ASSIGN ROLES TO USERS


GRANT ROLE ANALYST_ROLE
TO USER analyst_user;

GRANT ROLE DEVELOPER_ROLE
TO USER developer_user;

GRANT ROLE VIEWER_ROLE
TO USER viewer_user;


-- VERIFY ACCESS


SHOW GRANTS TO ROLE ANALYST_ROLE;

SHOW GRANTS TO ROLE DEVELOPER_ROLE;

SHOW GRANTS TO ROLE VIEWER_ROLE;

SHOW USERS;


-- TEST ROLE

GRANT ROLE ANALYST_ROLE
TO USER HARIBHARATHI;

USE ROLE ANALYST_ROLE;

SELECT * FROM MART.VW_TOTAL_SALES;