USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMM_DB;
USE SCHEMA CORE;

ALTER TABLE CORE_CUSTOMER
MODIFY COLUMN email
UNSET MASKING POLICY;

CREATE OR REPLACE MASKING POLICY EMAIL_MASK_POLICY
AS (val STRING)

RETURNS STRING ->

CASE

    WHEN CURRENT_ROLE() IN ('ADMIN_ROLE','ANALYST_ROLE')

    THEN val

    ELSE '********@gmail.com'

END;

ALTER TABLE CORE_CUSTOMER

MODIFY COLUMN email

SET MASKING POLICY EMAIL_MASK_POLICY;

DESC TABLE CORE_CUSTOMER;

SHOW MASKING POLICIES;

GRANT ROLE VIEWER_ROLE TO USER HARIBHARATHI;
GRANT ROLE ADMIN_ROLE TO USER HARIBHARATHI;

USE ROLE VIEWER_ROLE;

SELECT
customer_id,
customer_name,
email
FROM CORE_CUSTOMER;

USE ROLE ADMIN_ROLE;

SELECT
customer_id,
customer_name,
email
FROM CORE_CUSTOMER;